sudo: false
language: c
os: osx

addons:
  homebrew:
    packages:
    - z3
    - stack
    - upx

cache:
  directories:
  - $HOME/.stack
  - $HOME/.cabal/
  - $TRAVIS_BUILD_DIR/.stack-work
  - $TRAVIS_BUILD_DIR/submodules/brittany/.stack-work
  - $TRAVIS_BUILD_DIR/submodules/HaRe/.stack-work
  - $TRAVIS_BUILD_DIR/submodules/ghc-mod/.stack-work
  - $TRAVIS_BUILD_DIR/submodules/ghc-mod/core/.stack-work
  - $TRAVIS_BUILD_DIR/submodules/haskell-lsp/.stack-work
  - $TRAVIS_BUILD_DIR/submodules/haskell-lsp/haskell-lsp-types/.stack-work
  - $TRAVIS_BUILD_DIR/submodules/cabal-helper/.stack-work
  - $TRAVIS_BUILD_DIR/hie-plugin-api/.stack-work
  timeout: 800
before_cache:
  - rm -rf $TRAVIS_BUILD_DIR/.stack-work/logs/

stages:
  - setup
  - dependencies
  - test
  - deploy

jobs:
   include:
     - stage: setup
       env: GHC_VER="8.6.3"
       script: &setup
         - ls .stack-work/install/*/*/*/bin/hie || true
         - travis_retry stack --no-terminal --install-ghc --stack-yaml=stack-$GHC_VER.yaml setup
         # Build a big package to offload the next stage from doing too much work
         - stack --stack-yaml=stack-$GHC_VER.yaml build lens

     - stage: setup
       env: GHC_VER="8.4.4"
       script: *setup

     - stage: setup
       env: GHC_VER="8.4.3"
       script: *setup

     - stage: setup
       env: GHC_VER="8.4.2"
       script: *setup

     - stage: setup
       env: GHC_VER="8.2.2"
       script: *setup

     - stage: setup
       env: GHC_VER="8.2.1"
       script: *setup

     - stage: dependencies
       env: GHC_VER="8.6.3"
       script: &dependencies
         - travis_retry stack --no-terminal --install-ghc --stack-yaml=stack-$GHC_VER.yaml build --only-dependencies

     - stage: dependencies
       env: GHC_VER="8.4.4"
       script: *dependencies

     - stage: dependencies
       env: GHC_VER="8.4.3"
       script: *dependencies

     - stage: dependencies
       env: GHC_VER="8.4.2"
       script: *dependencies

     - stage: dependencies
       env: GHC_VER="8.2.2"
       script: *dependencies

     - stage: dependencies
       env: GHC_VER="8.2.1"
       script: *dependencies

     - stage: test
       env: GHC_VER="8.6.3"
       script: &test
         - stack --no-terminal --stack-yaml=stack-$GHC_VER.yaml install

     - stage: test
       env: GHC_VER="8.4.4"
       script: *test

     - stage: test
       env: GHC_VER="8.4.3"
       script: *test

     - stage: test
       env: GHC_VER="8.4.2"
       script: *test

     - stage: test
       env: GHC_VER="8.2.2"
       script: *test

     - stage: test
       env: GHC_VER="8.2.1"
       script: *test

     - stage: deploy
       env: GHC_VER="8.6.3"
       script: &deploy
         - mkdir -p $HOME/hie-macos
         - cp .stack-work/install/*/*/$GHC_VER/bin/hie $HOME/hie-macos
         - cp .stack-work/install/*/*/$GHC_VER/bin/hie-wrapper $HOME/hie-macos
         - upx --best $HOME/hie-macos/hie
         - upx --best $HOME/hie-macos/hie-wrapper
         - tar czf "hie-$GHC_VER-Darwin.tar.gz" $HOME/hie-macos
       deploy: &upload
         provider: releases
         api_key:
           secure: jhNwLD87iJZBA4yCd3bXUz4bcAxzPVTR7PjW9okQxXu5LBOYfTbUFsYCqnpEaItk1ot8WKwAxOt6tXkU/KkmDwhYCkii1Mt1r9mEKzDkjp68WhRlRm/3iCjlUcophXavUwcKZDtZHpii2bn+hne2Y8Eo8zbMIb1l5kd+mDH6WqP9AAMcgKSaHa7ZIkoc2S2TJ04nU8OeEW7Ts6lfOc6NAuxC9V28sewDUdWoAl8DIydsXvZWEAJ245Ir06zvg7KmdDuGmqHnO+cR2XjaRCs5sSDypexhECH+u8pgMe8Bziiy8aI1FHvRB8nEh/LvS+urGj1eoDH6DQiH+MerUFqFknn1wTw5fW9m3IsMpufVdlIMgQb1cqrr0osHyH9ckL/O7gtu7Fr67LXXPVq5TiUkIcLE6ut+DbCMs9LjePrHKW1JiEkqBBYB+MKkkKrPh3cUOjzuOkgnrpFgvFaBASSabqvVQvoDhCb+CxZQrSH1N1Qqj9zMuy6WFsmDmN/Pb940H3J9/isF/zkrPwrYbm02ZVV3882IEWuNGlr3NUW1Ik9lXPlPlen9BtJebaxhVa/RkRdyWIjk5Wlv9iGwuT/dtxqfJvD1EXodnxKAfc6QJISRwqpRBMIVIvRHRWOdY42AqHy/0NWG4J0gsTcBuBB4z5iwi9/zG7n60zcYU4N+9pg=
         file:
           - "hie-$GHC_VER-Darwin.tar.gz"
         skip_cleanup: true
         draft: true
         tag_name: "${TRAVIS_TAG}"
         on:
          tags: true

     - stage: deploy
       env: GHC_VER="8.4.4"
       script: *deploy
       deploy: *upload

     - stage: deploy
       env: GHC_VER="8.4.3"
       script: *deploy
       deploy: *upload

     - stage: deploy
       env: GHC_VER="8.4.2"
       script: *deploy
       deploy: *upload

     - stage: deploy
       env: GHC_VER="8.2.2"
       script: *deploy
       deploy: *upload

     - stage: deploy
       env: GHC_VER="8.2.1"
       script: *deploy
       deploy: *upload
